amcl:
  ros__parameters:

    use_sim_time: false

    # Frames
    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_link

    # Sensor
    scan_topic: /scan

    # Model of robot
    #robot_model_type: nav2_amcl::DifferentialMotionModel
    robot_model_type: nav2_amcl::OmniMotionModel

    # refresh rate 
    update_min_d: 0.05
    update_min_a: 0.05

    # Laser scan
    laser_min_range: 0.02
    laser_max_range: 20.0
    laser_model_type: likelihood_field

    # Particles
    min_particles: 500
    max_particles: 2000

    # Inicialization
    #set_initial_pose: false
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0


    # Publish
    tf_broadcast: true

    # Covarianzas / movimiento
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    # Beam model
    z_hit: 0.5
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.5
    sigma_hit: 0.2
    lambda_short: 0.1

    # Recuperation
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0